# Generated by Django 5.2.1 on 2025-06-02 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=20)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='solicitado_por',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='solicitacao',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='status',
        ),
        migrations.DeleteModel(
            name='Servidor',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='tipo_solicitação',
        ),
        migrations.RenameModel(
            old_name='Campus',
            new_name='Especialidade',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginasweb.especialidade'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginasweb.medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginasweb.paciente'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Historico',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
        migrations.DeleteModel(
            name='TipoSolicitacao',
        ),
    ]
