# Generated by Django 5.2.1 on 2025-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0002_consulta_medico_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
        ),
    ]
